# Site
name: "Carlos Outeiral"
title: "Carlos Outeiral's blog"
description: ""
# logo: 'assets/images/logo.png'
# favicon: 'assets/images/logo.png'
# baseurl: /mediumish-theme-jekyll
google_analytics: 'G-RY5LN103SB'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  sal:
    name: Carlos Outeiral
    avatar: 'assets/images/avatar.jpg'
    display_name: Carlos Outeiral
    email: carlos@outeiral.net
    web: https://carlos.outeiral.net
    twitter: https://twitter.com/c_outeiral
    description: "I am an Eric Schmidt <i>AI in Science</i> fellow at the University of Oxford, where I am also a Stipendiary Lecturer in Biochemistry. I write about AI, the future of pharma and biotechnology and, on occasion, social dancing."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
